devices:
  iphone:
    label: iPhone
    dimensions:
      width: 320
      height: 480
  android:
    label: Android
    dimensions:
      width: 540
      height: 960
  ipad:
    label: iPad
    dimensions:
      width: 768
      height: 1024
  desktop:
    label: desktop
    dimensions:
      width: 1366
      height: 768
